Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Layout/LineLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
